WIP: PHP 8.0 support & drop JMS v1.x support
liip/metadata-parser pull request #19
Opened 2021-02-28 19:03 UTC by Neur0toxine

I had to drop JMS v1.x support and update some packages to make it work on PHP 8.0. v3.x branch of the JMS serializer doesn't have any breaking changes which can affect this library. It should be perfectly usable with the 3.x branch.

2021-03-02 07:08 UTC, dbu requested changes
Thanks, this looks good! I agree with dropping JMS version 1 and adding JMS version 3, thats cool.
Can you please update the build matrix in .travis.yml so that we have a build with PHP 7.4 and 8.0?

Thanks for the upgrade to phpunit 9 as well. Can you try allowing phpunit 8 too? I guess it should work and that would allow to fix the builds on PHP 7.2 and 7.1.

I commented on a few minor things that i noticed.

2021-03-02 07:08 UTC, dbu commented on src/TypeParser/JMSTypeParser.php
> +        $this->jmsTypeParser = new Parser();
nice, thanks for the cleanup :+1:

2021-03-02 07:08 UTC, dbu commented on tests/BuilderTest.php
> +        static::assertCount(1, $props, 'Number of properties should match');
please revert these changes. i know they are static methods but the convention with phpunit has been to use `$this->`. i prefer to keep it that way to be consisten with other liip git repositories.

2021-03-02 18:51 UTC, Neur0toxine commented on composer.json
> +        "friendsofphp/php-cs-fixer": "^2.1",
This constraint is equivalent to `>=2.1 <3.0.0`. Actual version after executing `composer install` would be `v2.18.2`.

2021-03-02 18:54 UTC, Neur0toxine commented on src/Metadata/AbstractPropertyMetadata.php
> +    public function getCustomInformation(string $key): mixed
This has been added by `php-cs-fixer`. I'll disable this rule.

2021-03-02 18:59 UTC, Neur0toxine commented on src/Metadata/ParameterMetadata.php
> -     * @var mixed
This was removed by `php-cs-fixer` and was not intentional. Sorry for that. I'll disable those rules for now; the decision about the necessity of those rules is up to you.

2021-03-02 19:10 UTC, Neur0toxine commented
Thanks for the feedback! I fixed everything I could, but the PHPUnit version problem is harder to deal with. 8.x branch is not installable under PHP 8.0, but the 9.x branch requires PHP 7.3 or higher. I can use Symfony's [PHPUnit Bridge](https://symfony.com/doc/current/components/phpunit_bridge.html) to fix this. Let me know what you think about it, and if it sounds good to you - I'll do that.

2021-03-11 06:51 UTC, dbu commented on composer.json
> +        "friendsofphp/php-cs-fixer": "^2.1",
the problem with variable versions of the cs fixer is that the build randomly starts to fail when a rule in the cs fixer is changed. i prefer that upgrading the cs fixer is a deliberate decision.

2021-03-11 07:08 UTC, dbu commented on composer.json
> +        "phpunit/phpunit": "^9.5"
phpunit 9 only runs on php 7.3 and higher. can you allow phpunit 8 additionally?

2021-03-29 08:16 UTC, closed without merging

2021-03-29 08:17 UTC, dbu commented
thanks a lot! i wrapped things up in #20 and will tag 0.3.0 with this now